services:
  flaskapp:
    build:
      context: .
      dockerfile: Dockerfile-ppt
    environment:
      - "LITELLM_API_KEY=${LITELLM_API_KEY}"
      - "LLM_MODEL=${PPT_LLM_MODEL}"
      - "SECRET_KEY=${PPT_SECRET_KEY}"
      - "PEXELS_API_KEY=${PEXELS_API_KEY}"
    image: ppt
    container_name: ppt
    volumes:
      - ./ppt:/app/ppt
    ports:
      - "5001:5001"
