services:
  open-webui:
    environment:
      ENABLE_RAG_WEB_SEARCH: True
      # trunk-ignore(yamllint/quoted-strings)
      RAG_WEB_SEARCH_ENGINE: "searxng"
      RAG_WEB_SEARCH_RESULT_COUNT: 3
      RAG_WEB_SEARCH_CONCURRENT_REQUESTS: 10
      # trunk-ignore(yamllint/quoted-strings)
      SEARXNG_QUERY_URL: "http://searxng:8080/search?q=<query>"

  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      # trunk-ignore(yamllint/quoted-strings)
      - "5002:8080"
    volumes:
      - ./searxng:/etc/searxng
    restart: unless-stopped
