FROM python:3.11-slim

WORKDIR /app

COPY ./ppt/requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir -r /app/requirements.txt

COPY ./ppt /app/ppt

CMD ["python", "/app/ppt/myapp/flaskapp.py"]
